openapi: 3.0.2
info:
  title: FastAPI
  version: 0.1.0
paths:
  /:
    get:
      summary: Root
      operationId: root__get
      responses:
        '200':
          description: Successful Response
          content:
            application/json:
              schema: {}
  /api/v1/users:
    get:
      summary: Fetch Users
      operationId: fetch_users_api_v1_users_get
      responses:
        '200':
          description: Successful Response
          content:
            application/json:
              schema: {}
    post:
      summary: Add User
      operationId: add_user_api_v1_users_post
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/User'
        required: true
      responses:
        '200':
          description: Successful Response
          content:
            application/json:
              schema: {}
        '422':
          description: Validation Error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/HTTPValidationError'
components:
  schemas:
    Gender:
      title: Gender
      enum:
        - male
        - female
      type: string
      description: An enumeration.
    HTTPValidationError:
      title: HTTPValidationError
      type: object
      properties:
        detail:
          title: Detail
          type: array
          items:
            $ref: '#/components/schemas/ValidationError'
    Role:
      title: Role
      enum:
        - admin
        - user
        - student
      type: string
      description: An enumeration.
    User:
      title: User
      required:
        - first_name
        - last_name
        - gender
        - roles
      type: object
      properties:
        id:
          title: Id
          type: string
          format: uuid
          default: 51d90c15-ea5e-400d-8a3b-f8417f586cd5
        first_name:
          title: First Name
          type: string
        last_name:
          title: Last Name
          type: string
        middle_name:
          title: Middle Name
          type: string
        gender:
          $ref: '#/components/schemas/Gender'
        roles:
          type: array
          items:
            $ref: '#/components/schemas/Role'
    ValidationError:
      title: ValidationError
      required:
        - loc
        - msg
        - type
      type: object
      properties:
        loc:
          title: Location
          type: array
          items:
            anyOf:
              - type: string
              - type: integer
        msg:
          title: Message
          type: string
        type:
          title: Error Type
          type: string
